INSERT INTO dbx_uc_dedev.bdm_to_dbx_migration_meta.dc_entity_mstr (app_id,entity_id,entity_nm,raw_pre_processing_path,raw_post_processing_path,file_nm_validation_flg,file_nm,key_column_check_flg,key_column_list,column_header_check_flg,no_of_columns,mandatory_column_value_check_flg,mandatory_column_list,duplicate_value_check_flg,duplicate_check_column_list,file_delimeter,date_format_check_flg,date_format_column_list,decimal_value_check_flg,decimal_value_check_col_list,record_count_check_flg,data_element_enclosure_character,email,header,date_formats,parquet_header,encoding,no_validation_flag,parquet_key_col,tidal_job_id_contract,tidal_job_id_lake,skiprows,service,param_file_path,BU) VALUES
	 ('GEMATM01','ATM-HSS-DATA','ATM_HSS_SRC','tpc-aws-ted-dev-edpp-com-data-analytics-gem-eu-central-1/external/pre_contract/atm','tpc-aws-ted-dev-edpp-com-data-analytics-gem-eu-central-1/external/post_contract/atm','Y','ATM_HSS_all_data.xlsx','N','','Y','27','Y','Country|Organization|Project Title|Objective|Domain|Segment|Framework Element|Deliverables|Categories|Sub Category|Output/Outcome|Type (Number, Percentage)|Numerator|Denominator|Project Duration (Years)|Reporting Frequency|QuarterTarget|Quarter-Year|Target|Actual|Comments|Project Status|Start date (MM/YY)|Completion Date (MM/YY)|Report Date (MM/YY)|Quarter|Outcome','N','','','N','','N','','Y','','arn:aws:sns:eu-central-1:263789222982:CDP-EU-Com','Y','','country|organization|project_title|objective|domain|segment|framework_element|deliverables|categories|sub_category|output_outcome|type|numerator|denominator|project_duration_years|reporting_frequency|quartertarget|quarter_year|target|actual|comments|project_status|start_date|completion_date|report_date|quarter|outcome','','N','','108933','108935','',NULL,NULL,'COM'),
	 ('GEMATM01','ATM-TB-BRAND-MAPPING003','ATM_TB_BRAND_MAPPING_SRC','tpc-aws-ted-dev-edpp-raw-com-eu-central-1/de/gem/external/pre_contract','tpc-aws-ted-dev-edpp-raw-com-eu-central-1/de/gem/external/post_contract','Y','BRAND_MAPPING.xlsx','N','','Y','3','Y','Short form brand|Brand|Flag','N','','','N','','N','','Y','','arn:aws:sns:eu-central-1:263789222982:CDP-EU-Com','Y','','short_form_brand|brand|flag','',NULL,'','73112','73114','',NULL,NULL,'COM'),
	 ('GEMATM01','ATM-TB-COMIBNED-EXPORTS001','ATM_TB_COMIBNED_EXPORTS_SRC','tpc-aws-ted-dev-edpp-raw-com-eu-central-1/de/gem/external/pre_contract','tpc-aws-ted-dev-edpp-raw-com-eu-central-1/de/gem/external/post_contract','Y','COMBINED_EXPORTS_TAKEDA_GLOBAL_*.xlsx','N','','Y','45','Y','Country Name|Patients|Previous Patient ID|Status|Active|Area|Gender|Medication dosage|Unit|Second medication dosage (if applicable)|Unit_3|Indication|Prescription|Dropout reason|Dropout date|Application status|Process status|Referral|Consent document valid|Date of Referral|Patient program introduction|Introduction date|Medical eligibility|Medical eligibility date|Reason for medical non-eligibility|Financial eligibility|Financial eligibility date|Reason for financial non-eligibility|Patient interest|Interest date|Reason the patient is not interested|Financial interview|Calculated PFET|Program PFET|PFET appeal|Date patient is informed about financial results|Pre-Enrollment|Pre-Enrollment Date|Reason for no pre-enrollment|Enrollment|Enrollment Date|Validation of first cycle|Program Type|Duration of Treatment (DoT)|Comments','N','','','N','','N','','Y','','arn:aws:sns:eu-central-1:263789222982:CDP-EU-Com','Y','','country_name|patients|previous_patient_id|status|active|area|gender|medication_dosage|unit|second_medication_dosage|unit_3|indication|prescription|dropout_reason|dropout_date|application_status|process_status|referral|consent_document_valid|date_of_referral|patient_program_introduction|introduction_date|medical_eligibility|medical_eligibility_date|reason_for_medical_non_eligibility|financial_eligibility|financial_eligibility_date|reason_for_financial_non_eligibility|patient_interest|interest_date|reason_the_patient_is_not_interested|financial_interview|calculated _pfet|program_pfet|pfet_appeal|date_patient_is_informed_about_financial_results|pre_enrollment|pre_enrollment_date|reason_for_no_pre_enrollment|enrollment|enrollment_date|validation_of_first_cycle|program_type|duration_of_treatment|comments','',NULL,'','73104','73106','',NULL,NULL,'COM'),
	 ('GEMATM01','ATM-TB-COUNTRY-MAPPING004','ATM_TB_COUNTRY_MAPPING_SRC','tpc-aws-ted-dev-edpp-com-data-analytics-gem-eu-central-1/external/pre_contract/atm','tpc-aws-ted-dev-edpp-com-data-analytics-gem-eu-central-1/external/post_contract/atm','Y','COUNTRY_MAPPING.xlsx','N','','Y','5','Y','Area|Country|Short Name|CountryCode|Unique','N','','','N','','N','','Y','','arn:aws:sns:eu-central-1:263789222982:CDP-EU-Com','Y','','area|country|short_name|country_code|unique','',NULL,'','73116','73118','',NULL,NULL,'COM'),
	 ('GEMATM01','ATM-TB-DATA-COLLECTION-TEMPLATE-BVGH-UPDATED001','ATM_TB_DATA_COLLECTION_TEMPLATE_BVGH_UPDATED_SRC','tpc-aws-ted-dev-edpp-raw-com-eu-central-1/de/gem/external/pre_contract','tpc-aws-ted-dev-edpp-raw-com-eu-central-1/de/gem/external/post_contract','Y','DATA_COLLECTION_TEMPLATE_BVGH_UPDATED.xlsx','N','','N','28','N','','N','','','N','','N','','Y','','arn:aws:sns:eu-central-1:263789222982:CDP-EU-Com','Y','','project_title|country|organization|domain|segment|framework_element|indicator_name|output|type|numerator|denominator|project_duration|reporting_frequency|program_target|notes|q1-y1|q2-y1|q3-y1|q4-y1|q1-y2|q2-y2|q3-y2|q4-y2|q1-y3|q2-y3|q3-y3|q4-y3|dummy','',NULL,'','78203','78205','1',NULL,NULL,'COM'),
	 ('GEMATM01','ATM-TB-DATA-ENTRY002','ATM_TB_DATA_ENTRY_SRC','tpc-aws-ted-dev-edpp-raw-com-eu-central-1/de/gem/external/pre_contract','tpc-aws-ted-dev-edpp-raw-com-eu-central-1/de/gem/external/post_contract','Y','ATM_DATA_ENTRY.xlsx','N','','Y','29','Y','Area|Country|Brand|Dropout date|Referral|Date of Referral|Enrollment|Enrollment Date|Entered Date|Updated Date|Updated By|Name|Entered By|Email address|DataEntry Approval|DataEntry Approved Date|DataEntry Approved By|EntryID|Referred Count|Dropout Count|Active Count|FOC Vials|Purchased Vials|Date|Vial STP|CountryCode|BrandCode|__PowerAppsId__|Program Type','N','','','N','','N','','Y','','arn:aws:sns:eu-central-1:263789222982:CDP-EU-Com','Y','','area|country|brand|dropout_date|referral|date_of_referral|enrollment|enrollment_date|entered_date|updated_date|updated_by|name|entered_by|email_address|dataentry_approval|dataentry_approved_date|dataentry_approved_by|entryid|referred_count|dropout_count|active_count|foc_vials|purchased_vials|date|vial_stp|countrycode|brandcode|powerappsid|program_type','',NULL,'','73108','73110','',NULL,NULL,'COM'),
	 ('GEMATM01','ATM-TB-ICLUSIG-MONTHLY006','ATM_TB_TAKEDA_ICLUSIG_MONTHLY_PROGRAM_UPDATE_SRC','tpc-aws-ted-dev-edpp-raw-com-eu-central-1/de/gem/external/pre_contract','tpc-aws-ted-dev-edpp-raw-com-eu-central-1/de/gem/external/post_contract','Y','TAKEDA_ICLUSIG_MONTHLY_PROGRAM_UPDATE_*.xlsx','N','','Y','4','N','','N','','','N','','N','','Y','','arn:aws:sns:eu-central-1:263789222982:CDP-EU-Com','Y','noformat','country|number_of_active_patient_cases|number_of_closed_cases|number_of_case_approvals','',NULL,'','78120','78122','',NULL,NULL,'COM'),
	 ('GEMATM01','ATM-TB-TAKEDA-LSD-CAP-ACTIVE-PATIENT-ENROLLMENT007','ATM_TB_TAKEDA_LSD_CAP_ACTIVE_PATIENT_ENROLLMENT_SRC','tpc-aws-ted-dev-edpp-raw-com-eu-central-1/de/gem/external/pre_contract','tpc-aws-ted-dev-edpp-raw-com-eu-central-1/de/gem/external/post_contract','Y','TAKEDA_LSD_CAP_ACTIVE_PATIENT_ENROLLMENT_UPDATE_*.xlsx','Y','Country','Y','16','N','','Y','Country','','N','','N','','Y','','arn:aws:sns:eu-central-1:263789222982:CDP-EU-Com','Y','noformat','country|active_gaucher|active_fabry|active_mps_ii|active_hae|active_total_by_country|new_gaucher|new_fabry|new_mps_ii|new_hae|new_patients_total_by_country|dropout_gaucher|dropout_fabry|dropout_mps_ii|dropout_hae|dropped_out_patients_total_by_country','','','','76898','76900','','','','COM'),
	 ('GEMATM01','ATM-TB-TAKEDA-SUSTAINIBILITY005','ATM_TB_TAKEDA_SUSTAINIBILITY_SRC','tpc-aws-ted-dev-edpp-raw-com-eu-central-1/de/gem/external/pre_contract','tpc-aws-ted-dev-edpp-raw-com-eu-central-1/de/gem/external/post_contract','Y','TAKEDA_SUSTAINABILITY_ALL_TIME_*.csv','N','','Y','10','Y','Country|Treatment|Year|Month|PFET Score|Units-Com|Units-PSM (F,D)|Units-All|Program Type|Comments','N','',',','N','','N','','Y','','arn:aws:sns:eu-central-1:263789222982:CDP-EU-Com','Y','noformat','country|treatment|year|month|pfet_score|units_com|units_psm_fd|units_all|program_type|comments','',NULL,'','76329','76331','',NULL,NULL,'COM'),
	 ('GEMATM01','ATMALLTIME001','ATM_TAKEDA_SUSTAINIBILITY','tpc-aws-ted-dev-edpp-raw-com-eu-central-1/de/gem/external/pre_contract','tpc-aws-ted-dev-edpp-raw-com-eu-central-1/de/gem/external/post_contract','Y','TAKEDA_SUSTAINIBILITY_YYYYMM.csv','N','','N','8','N','Country|Treatment|Year|Month|PFET Score|Units-Com|Units-PSM (F,D)|Units-All','N','',',','N','','N','','Y','','arn:aws:sns:eu-central-1:263789222982:CDP-EU-Com','Y','noformat','country|treatment|year|month|pfet_score|units_com|units_psm_fd|units_all','',NULL,'','76329','76331','',NULL,NULL,'COM');

INSERT INTO dbx_uc_dedev.bdm_to_dbx_migration_meta.dc_load_strategy (entity_id,app_id,raw_source_file_path,lake_target_file_path,load_typ,BU) VALUES
	 ('ATM-HSS-DATA','GEMATM01','tpc-aws-ted-dev-edpp-com-data-analytics-gem-eu-central-1/external/post_contract/atm','tpc-aws-ted-dev-edpp-gpd-lake-gem-eu-central-1/de/atm/ATM_HSS_SRC','truncate','COM'),
	 ('ATM-TB-BRAND-MAPPING003','GEMATM01','tpc-aws-ted-dev-edpp-raw-com-eu-central-1/de/gem/external/post_contract','tpc-aws-ted-dev-edpp-lake-com-eu-central-1/de/ATM_TB_BRAND_MAPPING_SRC','truncate','COM'),
	 ('ATM-TB-COMIBNED-EXPORTS001','GEMATM01','tpc-aws-ted-dev-edpp-raw-com-eu-central-1/de/gem/external/post_contract','tpc-aws-ted-dev-edpp-lake-com-eu-central-1/de/ATM_TB_COMIBNED_EXPORTS_SRC','truncate','COM'),
	 ('ATM-TB-COUNTRY-MAPPING004','GEMATM01','tpc-aws-ted-dev-edpp-com-data-analytics-gem-eu-central-1/external/post_contract/atm','tpc-aws-ted-dev-edpp-lake-com-eu-central-1/de/ATM_TB_COUNTRY_MAPPING_SRC','truncate','COM'),
	 ('ATM-TB-DATA-COLLECTION-TEMPLATE-BVGH-UPDATED001','GEMATM01','tpc-aws-ted-dev-edpp-raw-com-eu-central-1/de/gem/external/post_contract','tpc-aws-ted-dev-edpp-lake-com-eu-central-1/de/ATM_TB_DATA_COLLECTION_TEMPLATE_BVGH_UPDATED_SRC','truncate','COM'),
	 ('ATM-TB-DATA-ENTRY002','GEMATM01','tpc-aws-ted-dev-edpp-raw-com-eu-central-1/de/gem/external/post_contract','tpc-aws-ted-dev-edpp-lake-com-eu-central-1/de/ATM_TB_DATA_ENTRY_SRC','truncate','COM'),
	 ('ATM-TB-ICLUSIG-MONTHLY006','GEMATM01','tpc-aws-ted-dev-edpp-raw-com-eu-central-1/de/gem/external/post_contract','tpc-aws-ted-dev-edpp-lake-com-eu-central-1/de/ATM_TB_TAKEDA_ICLUSIG_MONTHLY_PROGRAM_UPDATE_SRC','truncate','COM'),
	 ('ATM-TB-TAKEDA-LSD-CAP-ACTIVE-PATIENT-ENROLLMENT007','GEMATM01','tpc-aws-ted-dev-edpp-raw-com-eu-central-1/de/gem/external/post_contract','tpc-aws-ted-dev-edpp-lake-com-eu-central-1/de/ATM_TB_TAKEDA_LSD_CAP_ACTIVE_PATIENT_ENROLLMENT_SRC','truncate','COM'),
	 ('ATM-TB-TAKEDA-SUSTAINIBILITY005','GEMATM01','tpc-aws-ted-dev-edpp-raw-com-eu-central-1/de/gem/external/post_contract','tpc-aws-ted-dev-edpp-lake-com-eu-central-1/de/ATM_TB_TAKEDA_SUSTAINIBILITY_SRC','truncate','COM'),
	 ('ATMALLTIME001','GEMATM01','tpc-aws-ted-dev-edpp-raw-com-eu-central-1/de/gem/external/post_contract','tpc-aws-ted-dev-edpp-gpd-lake-eucan-eu-central-1/de/UK/hdsc_ac_47','truncate','COM');
